let inputWidth;
let inputHeight;
inputWidth = prompt("Enter your input width");
inputHeight = prompt("Enter your input height");
console.log(typeof inputWidth);
console.log(typeof inputHeight);
let width = parseInt(inputWidth);
let height = parseInt(inputHeight);
let area = width * height;
document.write("The area is: " + area);